import { Product } from './types';

export const products: Product[] = [
  // Electronics (20 items)
  {
    id: 1,
    name: "iPhone 14 Pro",
    price: 999.99,
    originalPrice: 1099.99,
    category: "electronics",
    brand: "apple",
    rating: 4.8,
    reviews: 245,
    image: "https://images.unsplash.com/photo-1592750475338-74b7b21085ab?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&h=600",
    description: "The latest iPhone with advanced camera system and A16 Bionic chip.",
    features: ["6.1-inch Super Retina XDR display", "A16 Bionic chip", "Pro camera system", "48MP Main camera"]
  },
  {
    id: 2,
    name: "Samsung Galaxy S23",
    price: 799.99,
    originalPrice: 899.99,
    category: "electronics",
    brand: "samsung",
    rating: 4.6,
    reviews: 189,
    image: "https://images.unsplash.com/photo-1610945265064-0e34e5519bbf?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&h=600",
    description: "Premium Android smartphone with exceptional camera capabilities.",
    features: ["6.1-inch Dynamic AMOLED display", "Snapdragon 8 Gen 2", "Triple camera system", "8K video recording"]
  },
  {
    id: 3,
    name: "MacBook Pro 14\"",
    price: 1999.99,
    originalPrice: 2199.99,
    category: "electronics",
    brand: "apple",
    rating: 4.9,
    reviews: 156,
    image: "https://images.unsplash.com/photo-1517336714731-489689fd1ca8?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&h=600",
    description: "Professional laptop with M2 Pro chip for demanding workflows.",
    features: ["14-inch Liquid Retina XDR display", "M2 Pro chip", "Up to 22 hours battery", "Advanced camera and audio"]
  },
  {
    id: 4,
    name: "Sony WH-1000XM4",
    price: 249.99,
    originalPrice: 349.99,
    category: "electronics",
    brand: "sony",
    rating: 4.7,
    reviews: 523,
    image: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&h=600",
    description: "Industry-leading noise canceling wireless headphones.",
    features: ["Active Noise Canceling", "30-hour battery life", "Touch controls", "High-resolution audio"]
  },
  {
    id: 5,
    name: "iPad Air",
    price: 599.99,
    originalPrice: 649.99,
    category: "electronics",
    brand: "apple",
    rating: 4.7,
    reviews: 321,
    image: "https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&h=600",
    description: "Powerful, colorful, and versatile iPad with M1 chip.",
    features: ["10.9-inch Liquid Retina display", "M1 chip", "12MP cameras", "All-day battery life"]
  },
  {
    id: 6,
    name: "Dell XPS 13",
    price: 1299.99,
    originalPrice: 1399.99,
    category: "electronics",
    brand: "dell",
    rating: 4.5,
    reviews: 203,
    image: "https://images.unsplash.com/photo-1496181133206-80ce9b88a853?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&h=600",
    description: "Ultra-portable laptop with stunning InfinityEdge display.",
    features: ["13.4-inch FHD+ display", "Intel Core i7", "16GB RAM", "512GB SSD"]
  },
  {
    id: 7,
    name: "AirPods Pro",
    price: 249.99,
    originalPrice: 279.99,
    category: "electronics",
    brand: "apple",
    rating: 4.6,
    reviews: 892,
    image: "https://images.unsplash.com/photo-1588423771073-b8903fbb85b5?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&h=600",
    description: "Active Noise Cancellation meets Personalized Spatial Audio.",
    features: ["Active Noise Cancellation", "Transparency mode", "Spatial Audio", "MagSafe Charging Case"]
  },
  {
    id: 8,
    name: "Samsung 55\" 4K TV",
    price: 899.99,
    originalPrice: 999.99,
    category: "electronics",
    brand: "samsung",
    rating: 4.4,
    reviews: 445,
    image: "https://images.unsplash.com/photo-1593359677879-a4bb92f829d1?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&h=600",
    description: "Crystal UHD 4K Smart TV with HDR10+.",
    features: ["55-inch 4K display", "Crystal Processor 4K", "Smart TV features", "HDR10+ support"]
  },
  {
    id: 9,
    name: "Google Pixel 7",
    price: 699.99,
    originalPrice: 799.99,
    category: "electronics",
    brand: "google",
    rating: 4.3,
    reviews: 312,
    image: "https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&h=600",
    description: "Google's flagship phone with advanced AI photography.",
    features: ["Google Tensor G2", "50MP main camera", "Magic Eraser", "All-day battery"]
  },
  {
    id: 10,
    name: "Nintendo Switch OLED",
    price: 349.99,
    originalPrice: 369.99,
    category: "electronics",
    brand: "nintendo",
    rating: 4.8,
    reviews: 623,
    image: "https://images.unsplash.com/photo-1606144042614-b2417e99c4e3?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&h=600",
    description: "Gaming console with vibrant OLED screen.",
    features: ["7-inch OLED screen", "Enhanced audio", "Wide adjustable stand", "64GB internal storage"]
  },
  
  // Fashion & Clothing (20 items)
  {
    id: 11,
    name: "Levi's 501 Jeans",
    price: 89.99,
    originalPrice: 119.99,
    category: "fashion",
    brand: "levis",
    rating: 4.3,
    reviews: 287,
    image: "https://images.unsplash.com/photo-1542272604-787c3835535d?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&h=600",
    description: "Classic straight-fit jeans made from premium denim.",
    features: ["100% cotton denim", "Classic straight fit", "Button fly", "Iconic styling"]
  },
  {
    id: 12,
    name: "Calvin Klein Dress Shirt",
    price: 69.99,
    originalPrice: 89.99,
    category: "fashion",
    brand: "calvinklein",
    rating: 4.1,
    reviews: 234,
    image: "https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&h=600",
    description: "Classic slim-fit dress shirt for professional occasions.",
    features: ["100% cotton", "Slim fit", "Wrinkle-resistant", "Machine washable"]
  },
  {
    id: 13,
    name: "Nike Hoodie",
    price: 79.99,
    originalPrice: 99.99,
    category: "fashion",
    brand: "nike",
    rating: 4.5,
    reviews: 456,
    image: "https://images.unsplash.com/photo-1556821840-3a63f95609a7?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&h=600",
    description: "Comfortable pullover hoodie with iconic swoosh logo.",
    features: ["Cotton blend fabric", "Kangaroo pocket", "Ribbed cuffs", "Classic fit"]
  },
  {
    id: 14,
    name: "Zara Blazer",
    price: 129.99,
    originalPrice: 159.99,
    category: "fashion",
    brand: "zara",
    rating: 4.2,
    reviews: 198,
    image: "https://images.unsplash.com/photo-1594633312681-425c7b97ccd1?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&h=600",
    description: "Elegant tailored blazer perfect for business or casual wear.",
    features: ["Tailored fit", "Notched lapels", "Two-button closure", "Side pockets"]
  },
  {
    id: 15,
    name: "H&M Summer Dress",
    price: 49.99,
    originalPrice: 69.99,
    category: "fashion",
    brand: "hm",
    rating: 4.0,
    reviews: 267,
    image: "https://images.unsplash.com/photo-1595777457583-95e059d581b8?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&h=600",
    description: "Light and airy summer dress in floral print.",
    features: ["Floral print", "Knee-length", "Short sleeves", "Breathable fabric"]
  },
  {
    id: 16,
    name: "Adidas Track Pants",
    price: 59.99,
    originalPrice: 79.99,
    category: "fashion",
    brand: "adidas",
    rating: 4.4,
    reviews: 334,
    image: "https://images.unsplash.com/photo-1544966503-7cc5ac882d5f?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&h=600",
    description: "Classic three-stripe track pants for casual wear.",
    features: ["Three-stripe design", "Elastic waistband", "Side pockets", "Tapered fit"]
  },
  {
    id: 17,
    name: "Ralph Lauren Polo",
    price: 89.99,
    originalPrice: 109.99,
    category: "fashion",
    brand: "ralphlauren",
    rating: 4.6,
    reviews: 189,
    image: "https://images.unsplash.com/photo-1586790170083-2f9ceadc732d?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&h=600",
    description: "Classic polo shirt with iconic pony logo.",
    features: ["100% cotton pique", "Two-button placket", "Ribbed collar", "Classic fit"]
  },
  {
    id: 18,
    name: "Uniqlo Thermal Wear",
    price: 29.99,
    originalPrice: 39.99,
    category: "fashion",
    brand: "uniqlo",
    rating: 4.3,
    reviews: 445,
    image: "https://images.unsplash.com/photo-1434389677669-e08b4cac3105?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&h=600",
    description: "Ultra-lightweight and warm thermal underwear.",
    features: ["Heattech fabric", "Moisture-wicking", "Odor control", "Seamless construction"]
  },
  {
    id: 19,
    name: "Tommy Hilfiger Jacket",
    price: 199.99,
    originalPrice: 249.99,
    category: "fashion",
    brand: "tommyhilfiger",
    rating: 4.5,
    reviews: 156,
    image: "https://images.unsplash.com/photo-1551028719-00167b16eac5?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&h=600",
    description: "Classic windbreaker jacket with signature flag logo.",
    features: ["Water-resistant", "Hood with drawstring", "Zip closure", "Side pockets"]
  },
  {
    id: 20,
    name: "Gap Chinos",
    price: 64.99,
    originalPrice: 84.99,
    category: "fashion",
    brand: "gap",
    rating: 4.2,
    reviews: 278,
    image: "https://images.unsplash.com/photo-1473966968600-fa801b869a1a?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&h=600",
    description: "Versatile chino pants perfect for any occasion.",
    features: ["Cotton twill fabric", "Slim fit", "Five-pocket styling", "Belt loops"]
  },

  // Sports & Fitness (15 items)
  {
    id: 21,
    name: "Nike Air Max 270",
    price: 129.99,
    originalPrice: 149.99,
    category: "sports",
    brand: "nike",
    rating: 4.5,
    reviews: 342,
    image: "https://images.unsplash.com/photo-1542291026-7eec264c27ff?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&h=600",
    description: "Comfortable running shoes with Max Air cushioning.",
    features: ["Max Air unit", "Lightweight design", "Durable rubber outsole", "Breathable mesh upper"]
  },
  {
    id: 22,
    name: "Adidas Ultraboost 22",
    price: 189.99,
    originalPrice: 219.99,
    category: "sports",
    brand: "adidas",
    rating: 4.4,
    reviews: 156,
    image: "https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&h=600",
    description: "Premium running shoes with responsive Boost cushioning.",
    features: ["Boost midsole", "Primeknit upper", "Continental rubber outsole", "Sock-like fit"]
  },
  {
    id: 23,
    name: "Under Armour HeatGear Shirt",
    price: 34.99,
    originalPrice: 44.99,
    category: "sports",
    brand: "underarmour",
    rating: 4.2,
    reviews: 89,
    image: "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&h=600",
    description: "Lightweight, breathable athletic shirt for peak performance.",
    features: ["HeatGear fabric", "Moisture-wicking", "Anti-odor technology", "4-way stretch"]
  },
  {
    id: 24,
    name: "Yoga Mat Premium",
    price: 49.99,
    originalPrice: 69.99,
    category: "sports",
    brand: "manduka",
    rating: 4.7,
    reviews: 523,
    image: "https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&h=600",
    description: "Professional-grade yoga mat with superior grip.",
    features: ["6mm thickness", "Non-slip surface", "Eco-friendly materials", "Lightweight"]
  },
  {
    id: 25,
    name: "Resistance Bands Set",
    price: 29.99,
    originalPrice: 39.99,
    category: "sports",
    brand: "bodylastics",
    rating: 4.3,
    reviews: 456,
    image: "https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&h=600",
    description: "Complete resistance training system with multiple bands.",
    features: ["5 resistance levels", "Door anchor included", "Protective sleeves", "Exercise guide"]
  },
  {
    id: 26,
    name: "Dumbbell Set 20kg",
    price: 99.99,
    originalPrice: 129.99,
    category: "sports",
    brand: "bowflex",
    rating: 4.6,
    reviews: 234,
    image: "https://images.unsplash.com/photo-1517963879433-6ad2b056d712?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&h=600",
    description: "Adjustable dumbbell set for home workouts.",
    features: ["Adjustable weight", "Space-saving design", "Quick-change mechanism", "Comfortable grip"]
  },
  {
    id: 27,
    name: "Basketball Wilson",
    price: 39.99,
    originalPrice: 49.99,
    category: "sports",
    brand: "wilson",
    rating: 4.4,
    reviews: 167,
    image: "https://images.unsplash.com/photo-1546519638-68e109498ffc?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&h=600",
    description: "Official size basketball with premium leather construction.",
    features: ["Official size and weight", "Composite leather", "Deep pebbling", "Butyl bladder"]
  },
  {
    id: 28,
    name: "Swimming Goggles",
    price: 24.99,
    originalPrice: 34.99,
    category: "sports",
    brand: "speedo",
    rating: 4.1,
    reviews: 289,
    image: "https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&h=600",
    description: "Professional swimming goggles with anti-fog coating.",
    features: ["Anti-fog coating", "UV protection", "Adjustable strap", "Comfortable seal"]
  },
  {
    id: 29,
    name: "Tennis Racket Pro",
    price: 149.99,
    originalPrice: 199.99,
    category: "sports",
    brand: "wilson",
    rating: 4.5,
    reviews: 145,
    image: "https://images.unsplash.com/photo-1551698618-1dfe5d97d256?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&h=600",
    description: "Professional tennis racket for serious players.",
    features: ["100 sq in head size", "16x19 string pattern", "11.2 oz weight", "Carbon fiber frame"]
  },
  {
    id: 30,
    name: "Protein Powder 2kg",
    price: 79.99,
    originalPrice: 99.99,
    category: "sports",
    brand: "optimum",
    rating: 4.6,
    reviews: 892,
    image: "https://images.unsplash.com/photo-1593095948071-474c5cc2989d?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&h=600",
    description: "Whey protein powder for muscle building and recovery.",
    features: ["25g protein per serving", "Fast absorption", "Multiple flavors", "Third-party tested"]
  },

  // Home & Garden (15 items)
  {
    id: 31,
    name: "Instant Pot Duo 7-in-1",
    price: 79.99,
    originalPrice: 99.99,
    category: "home",
    brand: "instant",
    rating: 4.6,
    reviews: 1245,
    image: "https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&h=600",
    description: "Multi-functional electric pressure cooker for quick and easy meals.",
    features: ["7-in-1 functionality", "6-quart capacity", "Safe and easy to use", "Free recipe app"]
  },
  {
    id: 32,
    name: "KitchenAid Stand Mixer",
    price: 379.99,
    originalPrice: 429.99,
    category: "home",
    brand: "kitchenaid",
    rating: 4.8,
    reviews: 567,
    image: "https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&h=600",
    description: "Professional-grade stand mixer for all your baking needs.",
    features: ["5-quart bowl", "10 speeds", "Tilt-head design", "Multiple attachments"]
  },
  {
    id: 33,
    name: "Dyson V11 Vacuum",
    price: 599.99,
    originalPrice: 699.99,
    category: "home",
    brand: "dyson",
    rating: 4.7,
    reviews: 423,
    image: "https://images.unsplash.com/photo-1558618047-3c8c76ca7d13?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&h=600",
    description: "Cordless vacuum with powerful suction and intelligent sensors.",
    features: ["Up to 60 minutes runtime", "LCD screen", "14 cyclones", "Converts to handheld"]
  },
  {
    id: 34,
    name: "Keurig Coffee Maker",
    price: 129.99,
    originalPrice: 159.99,
    category: "home",
    brand: "keurig",
    rating: 4.4,
    reviews: 789,
    image: "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&h=600",
    description: "Single-serve coffee maker with K-cup compatibility.",
    features: ["Multiple brew sizes", "Programmable", "Auto shut-off", "Large water reservoir"]
  },
  {
    id: 35,
    name: "Air Fryer XL",
    price: 89.99,
    originalPrice: 119.99,
    category: "home",
    brand: "ninja",
    rating: 4.5,
    reviews: 634,
    image: "https://images.unsplash.com/photo-1585937421612-70a008356fbe?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&h=600",
    description: "Large capacity air fryer for healthy cooking.",
    features: ["5.5-quart capacity", "Temperature control", "Non-stick basket", "Recipe book included"]
  },
  {
    id: 36,
    name: "Robot Vacuum",
    price: 299.99,
    originalPrice: 399.99,
    category: "home",
    brand: "roomba",
    rating: 4.3,
    reviews: 345,
    image: "https://images.unsplash.com/photo-1558618047-3c8c76ca7d13?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&h=600",
    description: "Smart robot vacuum with mapping technology.",
    features: ["Smart mapping", "WiFi connectivity", "Auto recharge", "Voice control"]
  },
  {
    id: 37,
    name: "Memory Foam Mattress",
    price: 499.99,
    originalPrice: 599.99,
    category: "home",
    brand: "casper",
    rating: 4.6,
    reviews: 567,
    image: "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&h=600",
    description: "Premium memory foam mattress for perfect sleep.",
    features: ["3-layer foam", "Motion isolation", "Temperature regulation", "100-night trial"]
  },
  {
    id: 38,
    name: "LED Desk Lamp",
    price: 49.99,
    originalPrice: 69.99,
    category: "home",
    brand: "philips",
    rating: 4.2,
    reviews: 234,
    image: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&h=600",
    description: "Adjustable LED desk lamp with USB charging.",
    features: ["Adjustable brightness", "USB charging port", "Touch control", "Eye-caring light"]
  },
  {
    id: 39,
    name: "Smart Thermostat",
    price: 199.99,
    originalPrice: 249.99,
    category: "home",
    brand: "nest",
    rating: 4.5,
    reviews: 456,
    image: "https://images.unsplash.com/photo-1558618047-3c8c76ca7d13?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&h=600",
    description: "Smart thermostat with learning capabilities.",
    features: ["Auto-schedule", "Remote control", "Energy saving", "Works with Alexa"]
  },
  {
    id: 40,
    name: "Blender Pro",
    price: 149.99,
    originalPrice: 199.99,
    category: "home",
    brand: "vitamix",
    rating: 4.7,
    reviews: 389,
    image: "https://images.unsplash.com/photo-1570197788417-0e82375c9371?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&h=600",
    description: "High-performance blender for smoothies and more.",
    features: ["Variable speed control", "Self-cleaning", "BPA-free", "7-year warranty"]
  },

  // Books & Media (10 items)
  {
    id: 41,
    name: "Atomic Habits Book",
    price: 14.99,
    originalPrice: 18.99,
    category: "books",
    brand: "penguin",
    rating: 4.8,
    reviews: 2345,
    image: "https://images.unsplash.com/photo-1544947950-fa07a98d237f?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&h=600",
    description: "Life-changing book about building good habits.",
    features: ["Practical strategies", "Scientific backing", "Easy to read", "Bestseller"]
  },
  {
    id: 42,
    name: "Kindle Paperwhite",
    price: 139.99,
    originalPrice: 159.99,
    category: "books",
    brand: "amazon",
    rating: 4.6,
    reviews: 1567,
    image: "https://images.unsplash.com/photo-1592496431122-2349e0fbc666?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&h=600",
    description: "Waterproof e-reader with adjustable warm light.",
    features: ["6.8 inch display", "Waterproof", "Weeks of battery", "Glare-free"]
  },
  {
    id: 43,
    name: "Python Programming Guide",
    price: 29.99,
    originalPrice: 39.99,
    category: "books",
    brand: "oreilly",
    rating: 4.4,
    reviews: 789,
    image: "https://images.unsplash.com/photo-1544947950-fa07a98d237f?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&h=600",
    description: "Comprehensive guide to Python programming.",
    features: ["Beginner friendly", "Code examples", "Practical projects", "Updated content"]
  },
  {
    id: 44,
    name: "The Great Gatsby",
    price: 12.99,
    originalPrice: 16.99,
    category: "books",
    brand: "scribner",
    rating: 4.2,
    reviews: 456,
    image: "https://images.unsplash.com/photo-1544947950-fa07a98d237f?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&h=600",
    description: "Classic American novel by F. Scott Fitzgerald.",
    features: ["Classic literature", "Hardcover edition", "Beautiful typography", "Timeless story"]
  },
  {
    id: 45,
    name: "Cookbook Collection",
    price: 24.99,
    originalPrice: 34.99,
    category: "books",
    brand: "taschen",
    rating: 4.5,
    reviews: 234,
    image: "https://images.unsplash.com/photo-1544947950-fa07a98d237f?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&h=600",
    description: "International recipes from around the world.",
    features: ["200+ recipes", "Beautiful photography", "Step-by-step instructions", "Dietary options"]
  },
  {
    id: 46,
    name: "Meditation Guide",
    price: 18.99,
    originalPrice: 24.99,
    category: "books",
    brand: "penguin",
    rating: 4.3,
    reviews: 567,
    image: "https://images.unsplash.com/photo-1544947950-fa07a98d237f?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&h=600",
    description: "Complete guide to mindfulness and meditation.",
    features: ["Practical techniques", "Scientific research", "Daily practices", "Stress relief"]
  },
  {
    id: 47,
    name: "Photography Handbook",
    price: 32.99,
    originalPrice: 42.99,
    category: "books",
    brand: "dkpublishing",
    rating: 4.6,
    reviews: 345,
    image: "https://images.unsplash.com/photo-1544947950-fa07a98d237f?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&h=600",
    description: "Complete guide to digital photography techniques.",
    features: ["Technical guidance", "Creative tips", "Equipment reviews", "Stunning examples"]
  },
  {
    id: 48,
    name: "Business Strategy Book",
    price: 26.99,
    originalPrice: 35.99,
    category: "books",
    brand: "harvard",
    rating: 4.4,
    reviews: 423,
    image: "https://images.unsplash.com/photo-1544947950-fa07a98d237f?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&h=600",
    description: "Essential strategies for business success.",
    features: ["Case studies", "Practical frameworks", "Expert insights", "Implementation guide"]
  },
  {
    id: 49,
    name: "Art History Textbook",
    price: 45.99,
    originalPrice: 59.99,
    category: "books",
    brand: "phaidon",
    rating: 4.5,
    reviews: 234,
    image: "https://images.unsplash.com/photo-1544947950-fa07a98d237f?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&h=600",
    description: "Comprehensive history of world art.",
    features: ["High-quality images", "Detailed analysis", "Timeline included", "Multiple periods"]
  },
  {
    id: 50,
    name: "Children's Story Collection",
    price: 19.99,
    originalPrice: 26.99,
    category: "books",
    brand: "scholastic",
    rating: 4.7,
    reviews: 678,
    image: "https://images.unsplash.com/photo-1544947950-fa07a98d237f?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&h=600",
    description: "Beloved children's stories with beautiful illustrations.",
    features: ["Colorful illustrations", "Age-appropriate", "Educational value", "Bedtime stories"]
  },

  // Health & Beauty (10 items)
  {
    id: 51,
    name: "Vitamin C Serum",
    price: 24.99,
    originalPrice: 34.99,
    category: "beauty",
    brand: "cerave",
    rating: 4.5,
    reviews: 789,
    image: "https://images.unsplash.com/photo-1556228578-8c89e6adf883?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&h=600",
    description: "Anti-aging serum with 20% Vitamin C.",
    features: ["Anti-aging", "Brightening", "Antioxidant protection", "Dermatologist tested"]
  },
  {
    id: 52,
    name: "Electric Toothbrush",
    price: 89.99,
    originalPrice: 119.99,
    category: "beauty",
    brand: "oral-b",
    rating: 4.6,
    reviews: 567,
    image: "https://images.unsplash.com/photo-1607613009820-a29f7bb81c04?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&h=600",
    description: "Smart electric toothbrush with pressure sensor.",
    features: ["Pressure sensor", "Multiple modes", "2-minute timer", "Travel case included"]
  },
  {
    id: 53,
    name: "Hair Dryer Pro",
    price: 149.99,
    originalPrice: 199.99,
    category: "beauty",
    brand: "dyson",
    rating: 4.7,
    reviews: 445,
    image: "https://images.unsplash.com/photo-1522338242992-e1a54906a8da?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&h=600",
    description: "Professional hair dryer with intelligent heat control.",
    features: ["Fast drying", "Heat protection", "Multiple attachments", "Quiet operation"]
  },
  {
    id: 54,
    name: "Moisturizer SPF 30",
    price: 18.99,
    originalPrice: 24.99,
    category: "beauty",
    brand: "neutrogena",
    rating: 4.3,
    reviews: 623,
    image: "https://images.unsplash.com/photo-1556228578-8c89e6adf883?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&h=600",
    description: "Daily moisturizer with broad-spectrum SPF protection.",
    features: ["SPF 30 protection", "Non-greasy", "All skin types", "12-hour hydration"]
  },
  {
    id: 55,
    name: "Makeup Brush Set",
    price: 39.99,
    originalPrice: 54.99,
    category: "beauty",
    brand: "morphe",
    rating: 4.4,
    reviews: 456,
    image: "https://images.unsplash.com/photo-1596462502278-27bfdc403348?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&h=600",
    description: "Professional makeup brush set with carrying case.",
    features: ["12 brushes included", "Synthetic bristles", "Travel case", "All purposes covered"]
  },
  {
    id: 56,
    name: "Essential Oils Set",
    price: 34.99,
    originalPrice: 49.99,
    category: "beauty",
    brand: "doterra",
    rating: 4.6,
    reviews: 345,
    image: "https://images.unsplash.com/photo-1608571423902-eed4a5ad8108?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&h=600",
    description: "Premium essential oils set for aromatherapy.",
    features: ["6 essential oils", "Pure and natural", "Therapeutic grade", "Usage guide included"]
  },
  {
    id: 57,
    name: "Face Cleanser",
    price: 16.99,
    originalPrice: 22.99,
    category: "beauty",
    brand: "cetaphil",
    rating: 4.2,
    reviews: 789,
    image: "https://images.unsplash.com/photo-1556228578-8c89e6adf883?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&h=600",
    description: "Gentle daily face cleanser for all skin types.",
    features: ["Gentle formula", "Non-comedogenic", "Fragrance-free", "Dermatologist recommended"]
  },
  {
    id: 58,
    name: "Hair Straightener",
    price: 79.99,
    originalPrice: 99.99,
    category: "beauty",
    brand: "ghd",
    rating: 4.5,
    reviews: 234,
    image: "https://images.unsplash.com/photo-1522338242992-e1a54906a8da?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&h=600",
    description: "Professional ceramic hair straightener.",
    features: ["Ceramic plates", "Temperature control", "Fast heat-up", "Auto shut-off"]
  },
  {
    id: 59,
    name: "Perfume Collection",
    price: 89.99,
    originalPrice: 119.99,
    category: "beauty",
    brand: "chanel",
    rating: 4.8,
    reviews: 567,
    image: "https://images.unsplash.com/photo-1541643600914-78b084683601?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&h=600",
    description: "Luxury perfume collection with three fragrances.",
    features: ["3 fragrances", "Long-lasting", "Gift packaging", "Travel sizes"]
  },
  {
    id: 60,
    name: "Jade Roller Set",
    price: 22.99,
    originalPrice: 32.99,
    category: "beauty",
    brand: "gua-sha",
    rating: 4.1,
    reviews: 345,
    image: "https://images.unsplash.com/photo-1556228578-8c89e6adf883?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&h=600",
    description: "Jade roller and gua sha set for facial massage.",
    features: ["Natural jade stone", "Face massage", "Reduces puffiness", "Instruction guide"]
  },

  // Toys & Games (10 items)
  {
    id: 61,
    name: "LEGO Creator Set",
    price: 79.99,
    originalPrice: 99.99,
    category: "toys",
    brand: "lego",
    rating: 4.8,
    reviews: 567,
    image: "https://images.unsplash.com/photo-1558060370-d140fe124625?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&h=600",
    description: "3-in-1 Creator set with multiple building options.",
    features: ["500+ pieces", "3 models in 1", "Ages 8+", "Building instructions"]
  },
  {
    id: 62,
    name: "Board Game Classic",
    price: 34.99,
    originalPrice: 44.99,
    category: "toys",
    brand: "hasbro",
    rating: 4.5,
    reviews: 423,
    image: "https://images.unsplash.com/photo-1606092195730-5d7b9af1efc5?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&h=600",
    description: "Classic board game for family fun.",
    features: ["2-6 players", "Ages 8+", "60-minute gameplay", "Strategy game"]
  },
  {
    id: 63,
    name: "Remote Control Car",
    price: 89.99,
    originalPrice: 119.99,
    category: "toys",
    brand: "traxxas",
    rating: 4.6,
    reviews: 345,
    image: "https://images.unsplash.com/photo-1558618047-3c8c76ca7d13?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&h=600",
    description: "High-speed remote control racing car.",
    features: ["30+ mph speed", "All-terrain", "Rechargeable battery", "Durable design"]
  },
  {
    id: 64,
    name: "Puzzle 1000 Pieces",
    price: 19.99,
    originalPrice: 26.99,
    category: "toys",
    brand: "ravensburger",
    rating: 4.4,
    reviews: 234,
    image: "https://images.unsplash.com/photo-1606092195730-5d7b9af1efc5?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&h=600",
    description: "Beautiful landscape puzzle with 1000 pieces.",
    features: ["1000 pieces", "High-quality printing", "Precision fit", "Finished size 27x20"]
  },
  {
    id: 65,
    name: "Action Figure Set",
    price: 49.99,
    originalPrice: 64.99,
    category: "toys",
    brand: "marvel",
    rating: 4.3,
    reviews: 456,
    image: "https://images.unsplash.com/photo-1558060370-d140fe124625?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&h=600",
    description: "Superhero action figure collection.",
    features: ["6 figures included", "Articulated joints", "Accessories", "Ages 4+"]
  },
  {
    id: 66,
    name: "Educational Tablet Kids",
    price: 129.99,
    originalPrice: 159.99,
    category: "toys",
    brand: "leapfrog",
    rating: 4.5,
    reviews: 678,
    image: "https://images.unsplash.com/photo-1558618047-3c8c76ca7d13?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&h=600",
    description: "Educational tablet designed for children.",
    features: ["Pre-loaded apps", "Parental controls", "Durable design", "Ages 3-9"]
  },
  {
    id: 67,
    name: "Science Experiment Kit",
    price: 39.99,
    originalPrice: 54.99,
    category: "toys",
    brand: "nationalgeographic",
    rating: 4.6,
    reviews: 345,
    image: "https://images.unsplash.com/photo-1558060370-d140fe124625?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&h=600",
    description: "Hands-on science experiments for kids.",
    features: ["20+ experiments", "Safety equipment", "Instruction guide", "Ages 8+"]
  },
  {
    id: 68,
    name: "Musical Keyboard",
    price: 79.99,
    originalPrice: 99.99,
    category: "toys",
    brand: "yamaha",
    rating: 4.4,
    reviews: 234,
    image: "https://images.unsplash.com/photo-1558060370-d140fe124625?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&h=600",
    description: "Electronic keyboard for young musicians.",
    features: ["61 keys", "Multiple sounds", "Built-in songs", "Recording function"]
  },
  {
    id: 69,
    name: "Art Supply Set",
    price: 44.99,
    originalPrice: 59.99,
    category: "toys",
    brand: "crayola",
    rating: 4.3,
    reviews: 567,
    image: "https://images.unsplash.com/photo-1558060370-d140fe124625?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&h=600",
    description: "Complete art supply set for creative kids.",
    features: ["100+ pieces", "Multiple mediums", "Storage case", "Ages 5+"]
  },
  {
    id: 70,
    name: "Drone Mini",
    price: 99.99,
    originalPrice: 129.99,
    category: "toys",
    brand: "dji",
    rating: 4.5,
    reviews: 423,
    image: "https://images.unsplash.com/photo-1558618047-3c8c76ca7d13?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&h=600",
    description: "Mini drone with camera for beginners.",
    features: ["HD camera", "Easy controls", "Safety features", "Flight time 15min"]
  },

  // Automotive (8 items)
  {
    id: 71,
    name: "Car Phone Mount",
    price: 24.99,
    originalPrice: 34.99,
    category: "automotive",
    brand: "iottie",
    rating: 4.4,
    reviews: 789,
    image: "https://images.unsplash.com/photo-1558618047-3c8c76ca7d13?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&h=600",
    description: "Universal car phone mount with wireless charging.",
    features: ["Wireless charging", "Adjustable", "One-touch release", "Dashboard mount"]
  },
  {
    id: 72,
    name: "Car Dash Camera",
    price: 89.99,
    originalPrice: 119.99,
    category: "automotive",
    brand: "garmin",
    rating: 4.5,
    reviews: 456,
    image: "https://images.unsplash.com/photo-1558618047-3c8c76ca7d13?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&h=600",
    description: "Full HD dash camera with night vision.",
    features: ["1080p recording", "Night vision", "G-sensor", "Loop recording"]
  },
  {
    id: 73,
    name: "Car Vacuum Cleaner",
    price: 49.99,
    originalPrice: 69.99,
    category: "automotive",
    brand: "blackdecker",
    rating: 4.2,
    reviews: 345,
    image: "https://images.unsplash.com/photo-1558618047-3c8c76ca7d13?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&h=600",
    description: "Portable car vacuum cleaner with accessories.",
    features: ["Cordless design", "Strong suction", "Multiple attachments", "Washable filter"]
  },
  {
    id: 74,
    name: "Jump Starter Kit",
    price: 79.99,
    originalPrice: 99.99,
    category: "automotive",
    brand: "anker",
    rating: 4.6,
    reviews: 567,
    image: "https://images.unsplash.com/photo-1558618047-3c8c76ca7d13?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&h=600",
    description: "Portable jump starter and power bank.",
    features: ["12V jump starter", "USB charging ports", "LED flashlight", "Safety protection"]
  },
  {
    id: 75,
    name: "Car Air Freshener",
    price: 12.99,
    originalPrice: 17.99,
    category: "automotive",
    brand: "littletrees",
    rating: 4.1,
    reviews: 234,
    image: "https://images.unsplash.com/photo-1558618047-3c8c76ca7d13?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&h=600",
    description: "Long-lasting car air freshener pack.",
    features: ["6-pack variety", "Long-lasting", "Fresh scents", "Easy to use"]
  },
  {
    id: 76,
    name: "Tire Pressure Gauge",
    price: 19.99,
    originalPrice: 26.99,
    category: "automotive",
    brand: "milton",
    rating: 4.3,
    reviews: 456,
    image: "https://images.unsplash.com/photo-1558618047-3c8c76ca7d13?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&h=600",
    description: "Digital tire pressure gauge with LED display.",
    features: ["Digital display", "Accurate readings", "LED backlight", "Auto shut-off"]
  },
  {
    id: 77,
    name: "Car Seat Covers",
    price: 59.99,
    originalPrice: 79.99,
    category: "automotive",
    brand: "fh-group",
    rating: 4.2,
    reviews: 345,
    image: "https://images.unsplash.com/photo-1558618047-3c8c76ca7d13?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&h=600",
    description: "Universal car seat covers set.",
    features: ["Universal fit", "Machine washable", "Airbag compatible", "Front and rear set"]
  },
  {
    id: 78,
    name: "USB Car Charger",
    price: 16.99,
    originalPrice: 22.99,
    category: "automotive",
    brand: "anker",
    rating: 4.5,
    reviews: 678,
    image: "https://images.unsplash.com/photo-1558618047-3c8c76ca7d13?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&h=600",
    description: "Fast charging USB car adapter.",
    features: ["Dual USB ports", "Fast charging", "LED indicator", "Compact design"]
  },

  // Office Supplies (8 items)
  {
    id: 79,
    name: "Ergonomic Office Chair",
    price: 249.99,
    originalPrice: 319.99,
    category: "office",
    brand: "herman-miller",
    rating: 4.6,
    reviews: 456,
    image: "https://images.unsplash.com/photo-1586023492125-27b2c045efd7?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&h=600",
    description: "Ergonomic office chair with lumbar support.",
    features: ["Lumbar support", "Adjustable height", "Mesh back", "5-year warranty"]
  },
  {
    id: 80,
    name: "Standing Desk",
    price: 399.99,
    originalPrice: 499.99,
    category: "office",
    brand: "flexispot",
    rating: 4.5,
    reviews: 345,
    image: "https://images.unsplash.com/photo-1586023492125-27b2c045efd7?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&h=600",
    description: "Height-adjustable standing desk converter.",
    features: ["Electric adjustment", "Memory presets", "Cable management", "Quiet motor"]
  },
  {
    id: 81,
    name: "Wireless Mouse",
    price: 39.99,
    originalPrice: 54.99,
    category: "office",
    brand: "logitech",
    rating: 4.4,
    reviews: 789,
    image: "https://images.unsplash.com/photo-1527814050087-3793815479db?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&h=600",
    description: "Precision wireless mouse with long battery life.",
    features: ["Wireless connectivity", "Precision tracking", "Long battery life", "Comfortable grip"]
  },
  {
    id: 82,
    name: "Mechanical Keyboard",
    price: 129.99,
    originalPrice: 159.99,
    category: "office",
    brand: "corsair",
    rating: 4.7,
    reviews: 567,
    image: "https://images.unsplash.com/photo-1527814050087-3793815479db?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&h=600",
    description: "RGB mechanical gaming keyboard.",
    features: ["Mechanical switches", "RGB backlighting", "Programmable keys", "Durable build"]
  },
  {
    id: 83,
    name: "Monitor 27 inch 4K",
    price: 299.99,
    originalPrice: 399.99,
    category: "office",
    brand: "lg",
    rating: 4.5,
    reviews: 423,
    image: "https://images.unsplash.com/photo-1527814050087-3793815479db?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&h=600",
    description: "27-inch 4K UHD monitor with USB-C.",
    features: ["4K UHD resolution", "USB-C connectivity", "HDR support", "Adjustable stand"]
  },
  {
    id: 84,
    name: "Desk Organizer Set",
    price: 34.99,
    originalPrice: 44.99,
    category: "office",
    brand: "bamboo",
    rating: 4.3,
    reviews: 234,
    image: "https://images.unsplash.com/photo-1586023492125-27b2c045efd7?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&h=600",
    description: "Bamboo desk organizer with multiple compartments.",
    features: ["Eco-friendly bamboo", "Multiple compartments", "Phone holder", "Pen storage"]
  },
  {
    id: 85,
    name: "Printer All-in-One",
    price: 179.99,
    originalPrice: 229.99,
    category: "office",
    brand: "canon",
    rating: 4.4,
    reviews: 567,
    image: "https://images.unsplash.com/photo-1612198188060-c7c2a3b66eae?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&h=600",
    description: "Wireless all-in-one inkjet printer.",
    features: ["Print, scan, copy", "Wireless connectivity", "Mobile printing", "Auto duplex"]
  },
  {
    id: 86,
    name: "Webcam HD",
    price: 89.99,
    originalPrice: 119.99,
    category: "office",
    brand: "logitech",
    rating: 4.6,
    reviews: 678,
    image: "https://images.unsplash.com/photo-1527814050087-3793815479db?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&h=600",
    description: "Full HD webcam with auto-focus.",
    features: ["1080p HD video", "Auto-focus", "Built-in microphone", "Privacy shutter"]
  },

  // Pet Supplies (8 items)
  {
    id: 87,
    name: "Dog Food Premium 15kg",
    price: 59.99,
    originalPrice: 74.99,
    category: "pets",
    brand: "royal-canin",
    rating: 4.7,
    reviews: 892,
    image: "https://images.unsplash.com/photo-1415369629372-26f2fe60c467?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&h=600",
    description: "Premium dry dog food for adult dogs.",
    features: ["High-quality protein", "Balanced nutrition", "No artificial colors", "Vet recommended"]
  },
  {
    id: 88,
    name: "Cat Litter Box Auto",
    price: 199.99,
    originalPrice: 249.99,
    category: "pets",
    brand: "petmate",
    rating: 4.4,
    reviews: 345,
    image: "https://images.unsplash.com/photo-1415369629372-26f2fe60c467?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&h=600",
    description: "Self-cleaning automatic litter box.",
    features: ["Self-cleaning", "Odor control", "Large capacity", "Easy maintenance"]
  },
  {
    id: 89,
    name: "Pet Carrier Travel",
    price: 79.99,
    originalPrice: 99.99,
    category: "pets",
    brand: "sherpa",
    rating: 4.5,
    reviews: 567,
    image: "https://images.unsplash.com/photo-1415369629372-26f2fe60c467?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&h=600",
    description: "Airline-approved pet travel carrier.",
    features: ["Airline approved", "Comfortable padding", "Ventilation", "Multiple sizes"]
  },
  {
    id: 90,
    name: "Dog Leash Retractable",
    price: 29.99,
    originalPrice: 39.99,
    category: "pets",
    brand: "flexi",
    rating: 4.3,
    reviews: 456,
    image: "https://images.unsplash.com/photo-1415369629372-26f2fe60c467?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&h=600",
    description: "Retractable dog leash with brake button.",
    features: ["16-foot length", "Brake button", "Comfortable grip", "Durable tape"]
  },
  {
    id: 91,
    name: "Cat Scratching Post",
    price: 49.99,
    originalPrice: 64.99,
    category: "pets",
    brand: "pioneer-pet",
    rating: 4.4,
    reviews: 234,
    image: "https://images.unsplash.com/photo-1415369629372-26f2fe60c467?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&h=600",
    description: "Multi-level cat scratching post with toys.",
    features: ["Natural sisal", "Multiple levels", "Hanging toys", "Stable base"]
  },
  {
    id: 92,
    name: "Pet Water Fountain",
    price: 44.99,
    originalPrice: 59.99,
    category: "pets",
    brand: "catmate",
    rating: 4.5,
    reviews: 345,
    image: "https://images.unsplash.com/photo-1415369629372-26f2fe60c467?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&h=600",
    description: "Automatic pet water fountain with filter.",
    features: ["Continuous circulation", "Carbon filter", "Quiet pump", "Easy to clean"]
  },
  {
    id: 93,
    name: "Dog Bed Orthopedic",
    price: 89.99,
    originalPrice: 119.99,
    category: "pets",
    brand: "furhaven",
    rating: 4.6,
    reviews: 567,
    image: "https://images.unsplash.com/photo-1415369629372-26f2fe60c467?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&h=600",
    description: "Orthopedic memory foam dog bed.",
    features: ["Memory foam", "Removable cover", "Machine washable", "Joint support"]
  },
  {
    id: 94,
    name: "Pet Grooming Kit",
    price: 39.99,
    originalPrice: 54.99,
    category: "pets",
    brand: "oster",
    rating: 4.3,
    reviews: 423,
    image: "https://images.unsplash.com/photo-1415369629372-26f2fe60c467?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&h=600",
    description: "Complete pet grooming kit with clippers.",
    features: ["Professional clippers", "Multiple guards", "Quiet operation", "Cordless"]
  },

  // Garden & Outdoor (6 items)
  {
    id: 95,
    name: "Garden Tool Set",
    price: 79.99,
    originalPrice: 99.99,
    category: "garden",
    brand: "fiskars",
    rating: 4.5,
    reviews: 456,
    image: "https://images.unsplash.com/photo-1416879595882-3373a0480b5b?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&h=600",
    description: "Essential garden tool set with carrying case.",
    features: ["7 tools included", "Ergonomic design", "Durable materials", "Storage case"]
  },
  {
    id: 96,
    name: "Plant Pots Set Ceramic",
    price: 44.99,
    originalPrice: 59.99,
    category: "garden",
    brand: "terra-cotta",
    rating: 4.4,
    reviews: 234,
    image: "https://images.unsplash.com/photo-1416879595882-3373a0480b5b?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&h=600",
    description: "Set of decorative ceramic plant pots.",
    features: ["5 pots included", "Drainage holes", "Decorative design", "Various sizes"]
  },
  {
    id: 97,
    name: "Garden Hose 50ft",
    price: 39.99,
    originalPrice: 54.99,
    category: "garden",
    brand: "flexzilla",
    rating: 4.6,
    reviews: 567,
    image: "https://images.unsplash.com/photo-1416879595882-3373a0480b5b?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&h=600",
    description: "Heavy-duty garden hose with spray nozzle.",
    features: ["50-foot length", "Kink resistant", "Spray nozzle", "Brass fittings"]
  },
  {
    id: 98,
    name: "Solar Garden Lights",
    price: 29.99,
    originalPrice: 39.99,
    category: "garden",
    brand: "brighttown",
    rating: 4.3,
    reviews: 345,
    image: "https://images.unsplash.com/photo-1416879595882-3373a0480b5b?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&h=600",
    description: "Solar-powered LED garden pathway lights.",
    features: ["Solar powered", "Auto on/off", "Weather resistant", "8-pack"]
  },
  {
    id: 99,
    name: "Bird Feeder Premium",
    price: 34.99,
    originalPrice: 44.99,
    category: "garden",
    brand: "perky-pet",
    rating: 4.4,
    reviews: 423,
    image: "https://images.unsplash.com/photo-1416879595882-3373a0480b5b?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&h=600",
    description: "Squirrel-proof bird feeder with multiple perches.",
    features: ["Squirrel-proof", "6 feeding ports", "Easy to fill", "Weather resistant"]
  },
  {
    id: 100,
    name: "Outdoor Furniture Set",
    price: 599.99,
    originalPrice: 749.99,
    category: "garden",
    brand: "polywood",
    rating: 4.7,
    reviews: 234,
    image: "https://images.unsplash.com/photo-1416879595882-3373a0480b5b?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&h=600",
    description: "Weather-resistant outdoor dining set.",
    features: ["Table and 4 chairs", "Weather resistant", "UV resistant", "Easy assembly"]
  }
];

export const categories = [
  { id: 'electronics', name: 'Electronics', icon: 'laptop' },
  { id: 'fashion', name: 'Fashion', icon: 'shirt' },
  { id: 'sports', name: 'Sports & Fitness', icon: 'dumbbell' },
  { id: 'home', name: 'Home & Garden', icon: 'home' },
  { id: 'books', name: 'Books & Media', icon: 'book' },
  { id: 'beauty', name: 'Health & Beauty', icon: 'heart' },
  { id: 'toys', name: 'Toys & Games', icon: 'gamepad2' },
  { id: 'automotive', name: 'Automotive', icon: 'car' },
  { id: 'office', name: 'Office Supplies', icon: 'briefcase' },
  { id: 'pets', name: 'Pet Supplies', icon: 'pawprint' },
  { id: 'garden', name: 'Garden & Outdoor', icon: 'trees' },
  { id: 'jewelry', name: 'Jewelry & Watches', icon: 'diamond' }
];

export const brands = [
  'apple',
  'samsung', 
  'nike',
  'sony',
  'levis',
  'instant',
  'adidas',
  'underarmour',
  'kitchenaid',
  'calvinklein'
];
